[build]
  publish = "_site"
  command = "npm run build"

[[plugins]]
  # package = "@netlify/plugin-lighthouse"

  # Optional, fails build when a category is below a threshold
  #[plugins.inputs.thresholds]
  #  performance = 1.0
  #  best-practices = 1.0
  #  seo = 1.0

  #[plugins.inputs]
  #  output_path = "reports/lighthouse/index.html"
